-- MySQL Workbench Synchronization
-- Generated: 2023-01-23 12:33
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Marina Royo Terol

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `S201_N1_E1` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Client` (
  `idClient` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_Client` VARCHAR(60) NOT NULL,
  `ID_Adreça` INT(10) UNSIGNED NOT NULL,
  `NumeroTelefon_client` TINYINT(3) UNSIGNED NOT NULL,
  `email_correu` VARCHAR(200) NOT NULL,
  `Data_registre` DATE NOT NULL,
  `Recomanat_client` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `Recomanat_client_UNIQUE` (`Recomanat_client` ASC) VISIBLE,
  UNIQUE INDEX `email_correu_UNIQUE` (`email_correu` ASC) VISIBLE,
  UNIQUE INDEX `NumeroTelefon_client_UNIQUE` (`NumeroTelefon_client` ASC) VISIBLE,
  UNIQUE INDEX `Nom_Client_UNIQUE` (`Nom_Client` ASC) VISIBLE,
  UNIQUE INDEX `ID_Adreça_UNIQUE` (`ID_Adreça` ASC) VISIBLE,
  CONSTRAINT `ID_Client_Recomanat`
    FOREIGN KEY (`Recomanat_client`)
    REFERENCES `S201_N1_E1`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_Adreça_Client`
    FOREIGN KEY (`ID_Adreça`)
    REFERENCES `S201_N1_E1`.`Adreça` (`ID_Adreça`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Ventes` (
  `ID_Ventes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Empleat` INT(10) UNSIGNED NOT NULL,
  `ID_Client` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Ventes`),
  UNIQUE INDEX `ID_Ventes_UNIQUE` (`ID_Ventes` ASC) VISIBLE,
  UNIQUE INDEX `ID_Empleat_UNIQUE` (`ID_Empleat` ASC) VISIBLE,
  UNIQUE INDEX `ID_Client_UNIQUE` (`ID_Client` ASC) VISIBLE,
  CONSTRAINT `ID_Empleat_Ventes`
    FOREIGN KEY (`ID_Empleat`)
    REFERENCES `S201_N1_E1`.`Empleat` (`ID_Empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Client_Ventes`
    FOREIGN KEY (`ID_Client`)
    REFERENCES `S201_N1_E1`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Empleat` (
  `ID_Empleat` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NomCognom_Empleat` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID_Empleat`),
  UNIQUE INDEX `idEmpleat_UNIQUE` (`ID_Empleat` ASC) VISIBLE,
  UNIQUE INDEX `NomCognom_Empleat_UNIQUE` (`NomCognom_Empleat` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Adreça` (
  `ID_Adreça` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Carrer` VARCHAR(70) NOT NULL,
  `Numero` TINYINT(3) UNSIGNED NOT NULL,
  `Pis` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `Porta` INT(3) UNSIGNED NULL DEFAULT NULL,
  `Ciutat` VARCHAR(45) NOT NULL,
  `Codi Postal` VARCHAR(10) NOT NULL,
  `País` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Adreça`),
  UNIQUE INDEX `idAdreça_UNIQUE` (`ID_Adreça` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Proveidor` (
  `ID_Proveidor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Adreça` INT(10) UNSIGNED NOT NULL,
  `Nom_Proveidor` VARCHAR(60) NOT NULL,
  `Telefon_Proveidor` TINYINT(13) UNSIGNED NOT NULL,
  `Fax_Proveidor` TINYINT(15) UNSIGNED NULL DEFAULT NULL,
  `NIF_Proveidor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Proveidor`),
  UNIQUE INDEX `ID_Proveidor_UNIQUE` (`ID_Proveidor` ASC) VISIBLE,
  UNIQUE INDEX `Nom_Proveidor_UNIQUE` (`Nom_Proveidor` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_Proveidor_UNIQUE` (`Telefon_Proveidor` ASC) VISIBLE,
  UNIQUE INDEX `Fax_Proveidor_UNIQUE` (`Fax_Proveidor` ASC) VISIBLE,
  UNIQUE INDEX `NIF_Proveidor_UNIQUE` (`NIF_Proveidor` ASC) VISIBLE,
  UNIQUE INDEX `ID_Adreça_UNIQUE` (`ID_Adreça` ASC) VISIBLE,
  CONSTRAINT `ID_Adreça_Proveidor`
    FOREIGN KEY (`ID_Adreça`)
    REFERENCES `S201_N1_E1`.`Adreça` (`ID_Adreça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Marca` (
  `ID_Marca` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Proveidor` INT(10) UNSIGNED NOT NULL,
  `Nom_Marca` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID_Marca`),
  UNIQUE INDEX `ID_Marca_UNIQUE` (`ID_Marca` ASC) VISIBLE,
  UNIQUE INDEX `Nom_Marca_UNIQUE` (`Nom_Marca` ASC) VISIBLE,
  UNIQUE INDEX `ID_Proveidor_UNIQUE` (`ID_Proveidor` ASC) VISIBLE,
  CONSTRAINT `ID_proveidor_Marca`
    FOREIGN KEY (`ID_Proveidor`)
    REFERENCES `S201_N1_E1`.`Proveidor` (`ID_Proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `S201_N1_E1`.`Ullera` (
  `ID_Ullera` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Marca` INT(10) UNSIGNED NOT NULL,
  `ID_Venta` INT(10) UNSIGNED NOT NULL,
  `Muntura_Ullera` ENUM('Flotant', 'Pasta', 'Metalica') NOT NULL,
  `Color_Muntura` VARCHAR(45) NOT NULL,
  `Color_Vidre_DRET` VARCHAR(45) NOT NULL,
  `Color_Vidre_ESQ` VARCHAR(45) NOT NULL,
  `Graduacio_DRET` FLOAT(10) UNSIGNED NOT NULL,
  `Graduacio_ESQ` FLOAT(10) UNSIGNED NOT NULL,
  `Preu` FLOAT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Ullera`),
  UNIQUE INDEX `ID_Ullera_UNIQUE` (`ID_Ullera` ASC) VISIBLE,
  UNIQUE INDEX `ID_Marca_UNIQUE` (`ID_Marca` ASC) VISIBLE,
  UNIQUE INDEX `ID_Venta_UNIQUE` (`ID_Venta` ASC) VISIBLE,
  CONSTRAINT `ID_marca_ullera`
    FOREIGN KEY (`ID_Marca`)
    REFERENCES `S201_N1_E1`.`Marca` (`ID_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_venta_ullera`
    FOREIGN KEY (`ID_Venta`)
    REFERENCES `S201_N1_E1`.`Ventes` (`ID_Ventes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
