-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 09:27:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProvincia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_Provincia` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localitat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Localitat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Localitat` (
  `idLocalitat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Provincia_Localitat` INT UNSIGNED NOT NULL,
  `Nom_Localitat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocalitat`),
  UNIQUE INDEX `idLocalitat_UNIQUE` (`idLocalitat` ASC) VISIBLE,
  CONSTRAINT `ID_Provincia_localitat`
    FOREIGN KEY (`ID_Provincia_Localitat`)
    REFERENCES `mydb`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Localitat_Client` INT UNSIGNED NOT NULL,
  `Nom_Client` VARCHAR(45) NOT NULL,
  `Cognom_Client` VARCHAR(80) NOT NULL,
  `Adreça_Client` VARCHAR(120) NOT NULL,
  `CodiPostal_Client` VARCHAR(5) NOT NULL,
  `Telefon_Client` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `Nom_Clients_UNIQUE` (`Nom_Client` ASC) VISIBLE,
  UNIQUE INDEX `Cognom_Clients_UNIQUE` (`Cognom_Client` ASC) VISIBLE,
  UNIQUE INDEX `Adreça_Clients_UNIQUE` (`Adreça_Client` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_Clients_UNIQUE` (`Telefon_Client` ASC) VISIBLE,
  CONSTRAINT `ID_Localitat_clients`
    FOREIGN KEY (`ID_Localitat_Client`)
    REFERENCES `mydb`.`Localitat` (`idLocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Botigues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Botigues` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Botigues` (
  `idBotigues` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Localitat` INT UNSIGNED NOT NULL,
  `Adreça_Botiga` VARCHAR(80) NOT NULL,
  `CodiPostal_Botiga` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idBotigues`),
  UNIQUE INDEX `idBotigues_UNIQUE` (`idBotigues` ASC) VISIBLE,
  CONSTRAINT `ID_Localitat_localitat`
    FOREIGN KEY (`ID_Localitat`)
    REFERENCES `mydb`.`Localitat` (`idLocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleats` (
  `idEmpleats` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Botiga` INT UNSIGNED NOT NULL,
  `Nom_Empleat` VARCHAR(35) NOT NULL,
  `Cognom_Empleat` VARCHAR(55) NOT NULL,
  `NIF_Empleat` VARCHAR(9) NOT NULL,
  `Telefon_Empleat` VARCHAR(15) NOT NULL,
  `Cuiner-Repartidor` ENUM('Cuiner', 'Repartidor') NOT NULL,
  PRIMARY KEY (`idEmpleats`),
  UNIQUE INDEX `idEmpleats_UNIQUE` (`idEmpleats` ASC) VISIBLE,
  UNIQUE INDEX `Nom_Empleat_UNIQUE` (`Nom_Empleat` ASC) VISIBLE,
  UNIQUE INDEX `Cognom_Empleat_UNIQUE` (`Cognom_Empleat` ASC) VISIBLE,
  UNIQUE INDEX `NIF_Empleat_UNIQUE` (`NIF_Empleat` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_Empleat_UNIQUE` (`Telefon_Empleat` ASC) VISIBLE,
  CONSTRAINT `ID_Botiga_empleats`
    FOREIGN KEY (`ID_Botiga`)
    REFERENCES `mydb`.`Botigues` (`idBotigues`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comandes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comandes` (
  `idComandes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Empleat` INT UNSIGNED NOT NULL,
  `ID_Client` VARCHAR(45) NULL,
  `Hora_Comanda` TIMESTAMP NOT NULL,
  `Recollir-Domicili` VARCHAR(45) NOT NULL,
  `Preu_Total` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idComandes`),
  UNIQUE INDEX `idComandes_UNIQUE` (`idComandes` ASC) VISIBLE,
  INDEX `ID_Client_idx` (`ID_Client` ASC) VISIBLE,
  CONSTRAINT `ID_Empleat_comanda`
    FOREIGN KEY (`ID_Empleat`)
    REFERENCES `mydb`.`Empleats` (`idEmpleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Client_comanda`
    FOREIGN KEY (`ID_Client`)
    REFERENCES `mydb`.`Clients` (`Nom_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cistella`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cistella` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cistella` (
  `idCistella` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Comanda` INT UNSIGNED NOT NULL,
  `Quantitat_Productes` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCistella`),
  UNIQUE INDEX `idProductes_UNIQUE` (`idCistella` ASC) VISIBLE,
  CONSTRAINT `ID_Comanda_cistella`
    FOREIGN KEY (`ID_Comanda`)
    REFERENCES `mydb`.`Comandes` (`idComandes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producte` (
  `idProducte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Cistella` INT UNSIGNED NOT NULL,
  `Nom_producte` VARCHAR(45) NOT NULL,
  `Descripcio_producte` VARCHAR(300) NOT NULL,
  `Imatge_producte` VARCHAR(45) NOT NULL,
  `Preu_Producte` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProducte`),
  UNIQUE INDEX `idProducte_UNIQUE` (`idProducte` ASC) VISIBLE,
  CONSTRAINT `ID_Cistella_producte`
    FOREIGN KEY (`ID_Cistella`)
    REFERENCES `mydb`.`Cistella` (`idCistella`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria_Pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_Pizza` (
  `idCategoria_Pizza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_Categoria` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCategoria_Pizza`),
  UNIQUE INDEX `idCategoria_Pizza_UNIQUE` (`idCategoria_Pizza` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cistella_has_Comandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cistella_has_Comandes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cistella_has_Comandes` (
  `Cistella_idCistella` INT UNSIGNED NOT NULL,
  `Comandes_idComandes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Cistella_idCistella`, `Comandes_idComandes`),
  INDEX `fk_Cistella_has_Comandes_Comandes1_idx` (`Comandes_idComandes` ASC) VISIBLE,
  INDEX `fk_Cistella_has_Comandes_Cistella1_idx` (`Cistella_idCistella` ASC) VISIBLE,
  CONSTRAINT `fk_Cistella_has_Comandes_Cistella1`
    FOREIGN KEY (`Cistella_idCistella`)
    REFERENCES `mydb`.`Cistella` (`idCistella`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cistella_has_Comandes_Comandes1`
    FOREIGN KEY (`Comandes_idComandes`)
    REFERENCES `mydb`.`Comandes` (`idComandes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producte_has_Categoria_Pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producte_has_Categoria_Pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producte_has_Categoria_Pizza` (
  `Producte_idProducte` INT UNSIGNED NOT NULL,
  `Categoria_Pizza_idCategoria_Pizza` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Producte_idProducte`, `Categoria_Pizza_idCategoria_Pizza`),
  INDEX `fk_Producte_has_Categoria_Pizza_Categoria_Pizza1_idx` (`Categoria_Pizza_idCategoria_Pizza` ASC) VISIBLE,
  INDEX `fk_Producte_has_Categoria_Pizza_Producte1_idx` (`Producte_idProducte` ASC) VISIBLE,
  CONSTRAINT `fk_Producte_has_Categoria_Pizza_Producte1`
    FOREIGN KEY (`Producte_idProducte`)
    REFERENCES `mydb`.`Producte` (`idProducte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producte_has_Categoria_Pizza_Categoria_Pizza1`
    FOREIGN KEY (`Categoria_Pizza_idCategoria_Pizza`)
    REFERENCES `mydb`.`Categoria_Pizza` (`idCategoria_Pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
